"use client"

import { useEffect, useState } from "react"
import Image from "next/image"
import Link from "next/link"

import Floating, { FloatingElement } from "@/components/ui/parallax-floating"
import { cn } from "@/lib/utils"
import { GALLERY_EVENTS } from "@/lib/gallery"
import { galleryBlur } from "@/lib/gallery-blur"

/**
 * Gallery wall — large parallax-floating photos, one per event, ordered by
 * recency (GALLERY_EVENTS is already newest-first). Each tile links straight
 * to its event page, mirroring the HND gallery's "wall of photos" pattern
 * instead of a filterable card grid.
 *
 * Per-item top offsets are computed (not hand-picked), so they're passed as
 * CSS custom properties via `style`, not interpolated into Tailwind
 * arbitrary-value classes — a class string built from a JS variable never
 * gets scanned/generated by Tailwind. The class list itself stays a fixed
 * literal (`top-(--wall-top-m)`); only the custom-property *value*
 * varies per item.
 */
interface WallItem {
  slug: string
  name: string
  cover: string
  aspect: "3/2" | "4/5"
  depth: number
  isLeft: boolean
  topMobile: number
  topDesktop: number
}

// Tile width, in vw, per breakpoint — smaller tile = smaller number here,
// everything else (heights, gaps, centering) derives from it.
const DESKTOP_TILE_VW = 32
const DESKTOP_COL_GAP_VW = 4
const DESKTOP_LEFT_PCT = (100 - (DESKTOP_TILE_VW * 2 + DESKTOP_COL_GAP_VW)) / 2
const DESKTOP_RIGHT_PCT =
  DESKTOP_LEFT_PCT + DESKTOP_TILE_VW + DESKTOP_COL_GAP_VW
const MOBILE_TILE_VW = 65
const MOBILE_LEFT_PCT = (100 - MOBILE_TILE_VW) / 2

const ASPECT_RATIO = { "3/2": 1.5, "4/5": 0.8 } as const
const ASPECTS: WallItem["aspect"][] = [
  "4/5",
  "3/2",
  "3/2",
  "3/2",
  "4/5",
  "4/5",
  "4/5",
]
const DEPTHS = [3, 2, 4, 1, 1, 2.5, 1.5]

// Running totals are tracked in vw (a real physical unit) so each item's
// height can be derived from its aspect ratio, then converted to a
// percentage of the container's own height at the end — `top-%` is a
// percentage of the *container's* height, so raw vw offsets can't be used
// as the percentage value directly unless the container happens to be
// exactly 100vw tall. The container's own height (also needed as a CSS
// value) is exactly the same total these percentages are relative to, so
// both come out of this one pass.
function buildWall(): {
  items: WallItem[]
  mobileHeightVw: number
  desktopHeightVw: number
} {
  const events = GALLERY_EVENTS.slice(0, 7)
  let leftTopVw = 3
  let rightTopVw = 20
  let mobileTopVw = 2

  // Each tile is the image plus a caption row (~32px of mt-3 + text) below
  // it — the gap has to clear that too, not just the image's own height, or
  // the next column-mate's image creeps up under the caption.
  const CAPTION_GAP_DESKTOP_VW = 7
  const CAPTION_GAP_MOBILE_VW = 15

  const raw = events.map((event, i) => {
    const aspect = ASPECTS[i]
    const isLeft = i % 2 === 0
    const desktopTopVw = isLeft ? leftTopVw : rightTopVw
    const desktopHeightVw = DESKTOP_TILE_VW / ASPECT_RATIO[aspect]
    if (isLeft) leftTopVw += desktopHeightVw + CAPTION_GAP_DESKTOP_VW
    else rightTopVw += desktopHeightVw + CAPTION_GAP_DESKTOP_VW

    const mobileHeightVw = MOBILE_TILE_VW / ASPECT_RATIO[aspect]
    const topMobileVw = mobileTopVw
    mobileTopVw += mobileHeightVw + CAPTION_GAP_MOBILE_VW

    return {
      event,
      aspect,
      isLeft,
      topMobileVw,
      topDesktopVw: desktopTopVw,
      desktopHeightVw,
    }
  })

  const mobileHeightVw = mobileTopVw + CAPTION_GAP_MOBILE_VW
  const desktopHeightVw =
    Math.max(leftTopVw, rightTopVw) + CAPTION_GAP_DESKTOP_VW

  const items = raw.map((r, i) => ({
    slug: r.event.slug,
    name: r.event.name,
    cover: r.event.cover,
    aspect: r.aspect,
    depth: DEPTHS[i],
    isLeft: r.isLeft,
    topMobile: (r.topMobileVw / mobileHeightVw) * 100,
    topDesktop: (r.topDesktopVw / desktopHeightVw) * 100,
  }))

  return { items, mobileHeightVw, desktopHeightVw }
}

const {
  items: WALL_ITEMS,
  mobileHeightVw: MOBILE_WALL_HEIGHT_VW,
  desktopHeightVw: DESKTOP_WALL_HEIGHT_VW,
} = buildWall()

export function FloatingWall() {
  const [isTouch, setIsTouch] = useState(false)

  useEffect(() => {
    const mq = window.matchMedia("(hover: none), (pointer: coarse)")
    const applyTouch = () => setIsTouch(mq.matches)
    applyTouch()
    mq.addEventListener("change", applyTouch)
    return () => mq.removeEventListener("change", applyTouch)
  }, [])

  return (
    <div className="bg-background relative">
      {/* Mobile — the wall as a staggered vertical column, same events in the
          same order. Alternating left/right offset and a slight rotation echo
          the desktop wall's scattered composition; a bigger drop + scale on
          press (not just hover, which a touch screen never fires) signals the
          tile is tappable. Both branches sit in the DOM and swap with CSS —
          the images are lazy, so the hidden branch never fetches one. */}
      <div className="flex flex-col gap-10 px-6 pt-2 pb-12 md:hidden">
        {WALL_ITEMS.map((item, i) => (
          <Link
            key={item.slug}
            href={`/gallery/${item.slug}`}
            className={cn(
              "focus-visible:ring-brand w-[72vw] transition-transform duration-200 ease-out outline-none focus-visible:ring-2 active:scale-[0.96]",
              i % 2 === 0
                ? "rotate-[-1.5deg] self-start"
                : "rotate-[1.5deg] self-end"
            )}
          >
            <div
              className="relative w-full overflow-hidden rounded-3xl shadow-lg shadow-black/15"
              style={{ aspectRatio: item.aspect }}
            >
              <Image
                src={item.cover}
                alt={item.name}
                fill
                sizes="72vw"
                className="object-cover"
                {...galleryBlur(item.cover)}
              />
            </div>
            <div className="mt-3 flex items-baseline justify-between gap-3">
              <span className="text-foreground line-clamp-1 text-sm font-medium">
                {item.name}
              </span>
              <span className="after:bg-foreground relative shrink-0 text-sm font-medium after:absolute after:bottom-0 after:left-0 after:h-px after:w-full">
                Visit
              </span>
            </div>
          </Link>
        ))}
      </div>

      <div
        className="relative z-0 hidden w-full overflow-hidden md:block"
        style={
          {
            "--wall-h-m": `${MOBILE_WALL_HEIGHT_VW}vw`,
            "--wall-h-d": `${DESKTOP_WALL_HEIGHT_VW}vw`,
          } as React.CSSProperties
        }
      >
        <div className="min-h-(--wall-h-m) md:min-h-(--wall-h-d)" />
        <div className="absolute inset-0">
          <Floating sensitivity={-0.15}>
            {WALL_ITEMS.map((item, i) => (
              <FloatingElement
                key={item.slug}
                depth={item.depth}
                className={cn(
                  "top-(--wall-top-m) left-(--wall-left-m) w-(--wall-w-m)",
                  "md:top-(--wall-top-d) md:left-(--wall-left-d) md:w-(--wall-w-d)"
                )}
                style={
                  {
                    "--wall-top-m": `${item.topMobile}%`,
                    "--wall-top-d": `${item.topDesktop}%`,
                    "--wall-left-m": `${MOBILE_LEFT_PCT}%`,
                    "--wall-left-d": `${item.isLeft ? DESKTOP_LEFT_PCT : DESKTOP_RIGHT_PCT}%`,
                    "--wall-w-m": `${MOBILE_TILE_VW}vw`,
                    "--wall-w-d": `${DESKTOP_TILE_VW}vw`,
                  } as React.CSSProperties
                }
              >
                <Link
                  href={`/gallery/${item.slug}`}
                  data-gallery-photo
                  tabIndex={0}
                  style={{ "--tile-i": i } as React.CSSProperties}
                  className="animate-wall-tile-in group focus-visible:ring-brand isolate block cursor-pointer outline-none focus-visible:z-10 focus-visible:ring-2"
                >
                  <div
                    className="relative w-full origin-bottom overflow-hidden rounded-3xl border border-transparent transition-transform duration-700 ease-[cubic-bezier(0.22,1,0.36,1)] md:group-hover:scale-[1.04] md:group-focus-visible:scale-[1.04]"
                    style={{ aspectRatio: item.aspect }}
                  >
                    <Image
                      src={item.cover}
                      alt={item.name}
                      fill
                      sizes={`(min-width: 768px) ${DESKTOP_TILE_VW}vw, ${MOBILE_TILE_VW}vw`}
                      className="object-cover"
                      {...galleryBlur(item.cover)}
                    />
                  </div>

                  <div className="mt-3 flex items-baseline justify-between gap-3">
                    <span className="text-foreground text-sm font-medium">
                      {item.name}
                    </span>
                    <span
                      className={cn(
                        "text-foreground relative text-sm font-medium transition-opacity duration-200",
                        "after:bg-foreground after:absolute after:bottom-0 after:left-0 after:h-px after:w-full after:origin-left after:scale-x-0 after:transition-transform after:duration-300",
                        isTouch
                          ? "opacity-100 after:scale-x-100"
                          : "pointer-events-none opacity-0 md:group-hover:pointer-events-auto md:group-hover:opacity-100 md:group-focus-visible:pointer-events-auto md:group-focus-visible:opacity-100 md:group-hover:after:scale-x-100 md:group-focus-visible:after:scale-x-100"
                      )}
                    >
                      Visit
                    </span>
                  </div>
                </Link>
              </FloatingElement>
            ))}
          </Floating>
        </div>
      </div>
    </div>
  )
}
